/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LDSHR_H_RPCGEN
#define _LDSHR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct node {
	struct node *next;
	double val;
};
typedef struct node node;

typedef node HEADNODE;

struct data_shape {
	int N;
	int M;
	int S;
};
typedef struct data_shape data_shape;

#define LDSHRPROG 0x2228012
#define LDSHRVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETLOAD 1
extern  HEADNODE * getload_1(HEADNODE *, CLIENT *);
extern  HEADNODE * getload_1_svc(HEADNODE *, struct svc_req *);
#define FINDMAX_GPU 2
extern  double * findmax_gpu_1(struct data_shape *, CLIENT *);
extern  double * findmax_gpu_1_svc(struct data_shape *, struct svc_req *);
#define UPDATE_LST 3
extern  HEADNODE * update_lst_1(HEADNODE *, CLIENT *);
extern  HEADNODE * update_lst_1_svc(HEADNODE *, struct svc_req *);
extern int ldshrprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETLOAD 1
extern  HEADNODE * getload_1();
extern  HEADNODE * getload_1_svc();
#define FINDMAX_GPU 2
extern  double * findmax_gpu_1();
extern  double * findmax_gpu_1_svc();
#define UPDATE_LST 3
extern  HEADNODE * update_lst_1();
extern  HEADNODE * update_lst_1_svc();
extern int ldshrprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_node (XDR *, node*);
extern  bool_t xdr_HEADNODE (XDR *, HEADNODE*);
extern  bool_t xdr_data_shape (XDR *, data_shape*);

#else /* K&R C */
extern bool_t xdr_node ();
extern bool_t xdr_HEADNODE ();
extern bool_t xdr_data_shape ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LDSHR_H_RPCGEN */
