/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ldshr.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
ldshrprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		HEADNODE getload_1_arg;
		struct data_shape findmax_gpu_1_arg;
		HEADNODE update_lst_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GETLOAD:
		_xdr_argument = (xdrproc_t) xdr_HEADNODE;
		_xdr_result = (xdrproc_t) xdr_HEADNODE;
		local = (char *(*)(char *, struct svc_req *)) getload_1_svc;
		break;

	case FINDMAX_GPU:
		_xdr_argument = (xdrproc_t) xdr_data_shape;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) findmax_gpu_1_svc;
		break;

	case UPDATE_LST:
		_xdr_argument = (xdrproc_t) xdr_HEADNODE;
		_xdr_result = (xdrproc_t) xdr_HEADNODE;
		local = (char *(*)(char *, struct svc_req *)) update_lst_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (LDSHRPROG, LDSHRVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, LDSHRPROG, LDSHRVERS, ldshrprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (LDSHRPROG, LDSHRVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, LDSHRPROG, LDSHRVERS, ldshrprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (LDSHRPROG, LDSHRVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
