/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ldshr.h"

bool_t
xdr_node (XDR *xdrs, node *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (node), (xdrproc_t) xdr_node))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->val))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_HEADNODE (XDR *xdrs, HEADNODE *objp)
{
	register int32_t *buf;

	 if (!xdr_node (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data_shape (XDR *xdrs, data_shape *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->N))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->M))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->S))
		 return FALSE;
	return TRUE;
}
