/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "ldshr.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

HEADNODE *
getload_1(HEADNODE *argp, CLIENT *clnt)
{
	static HEADNODE clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETLOAD,
		(xdrproc_t) xdr_HEADNODE, (caddr_t) argp,
		(xdrproc_t) xdr_HEADNODE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

double *
findmax_gpu_1(struct data_shape *argp, CLIENT *clnt)
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FINDMAX_GPU,
		(xdrproc_t) xdr_data_shape, (caddr_t) argp,
		(xdrproc_t) xdr_double, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

HEADNODE *
update_lst_1(HEADNODE *argp, CLIENT *clnt)
{
	static HEADNODE clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, UPDATE_LST,
		(xdrproc_t) xdr_HEADNODE, (caddr_t) argp,
		(xdrproc_t) xdr_HEADNODE, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
